[env]
TERM = "alacritty"

[window]
decorations = "None"
startup_mode = "Windowed"
title = "Terminal"
opacity = 0.95
padding.x = 8
padding.y = 8 
dynamic_padding = false 

[scrolling]
history = 10_000

[font]
size = 14

  [font.bold]
  style = "Normal"

  [font.offset]
  x = 0
  y = -1

[colors.primary]
background = "0x1a1e2a"
foreground = "0xffffff"

[colors.normal]
black = "0x1d2430"
red = "0xfa5ead"
green = "0x00fbad"
yellow = "0xffdf5f"
cyan = "0x242d42"
magenta = "0xfa5ead"
blue = "0x5eadfc"
white = "0xffffff"

[colors.bright]
black = "0x1d2430"
red = "0xfa5ead"
green = "0x00fbad"
yellow = "0xffdf5f"
cyan = "0x6a6f87"
magenta = "0xfa5ead"
blue = "0x5eadfc"
white = "0xeff1f5"

[selection]
save_to_clipboard = true

[cursor]
style = "Block"

