[env]
TERM = "alacritty"

[window]
decorations = "full"
startup_mode = "Windowed"
title = "Terminal"
opacity = 0.9

  [window.padding]
  x = 8
  y = 15

[scrolling]
history = 10_000

[font]
size = 10

  [font.bold]
  style = "Normal"

  [font.offset]
  x = 0
  y = -1

[colors.primary]
background = "0x1a1e2a"
foreground = "0xffffff"

[colors.normal]
black = "0x1d2430"
red = "0xfa5ead"
green = "0x00fbad"
yellow = "0xffdf5f"
blue = "0x5eadfc"
magenta = "0xfa5ead"
cyan = "0x242D42"
white = "0xffffff"

[colors.bright]
black = "0x1d2430"
red = "0xfa5ead"
green = "0x00fbad"
yellow = "0xffdf5f"
blue = "0x5eadfc"
magenta = "0xfa5ead"
cyan = "0x6a6f87"
white = "0xeff1f5"

[selection]
save_to_clipboard = true

[cursor]
style = "Block"

